import { test, expect } from '@playwright/test'

test('real topology coverage, driving activity and stable scene', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/api/**', async route => {
    const url = route.request().url().replace(/http:\/\/127\.0\.0\.1:5174/, 'http://127.0.0.1:8000')
    await route.continue({ url })
  })
  await page.goto('http://127.0.0.1:5174/')
  await expect(page.locator('.canvas-host canvas')).toBeVisible({ timeout: 120000 })
  await expect(page.getByText('BODY 10059', { exact: true })).toBeVisible()
  const canvas = page.locator('.canvas-host canvas')
  await canvas.evaluate(el => el.setAttribute('data-scene-instance', 'original'))
  await page.getByRole('button', { name: '完整拓扑图' }).click()
  const svg = page.getByLabel('全通路拓扑图')
  await expect(svg).toHaveAttribute('data-edge-coverage', '25582938')
  expect(await svg.locator('path[data-source]').count()).toBeGreaterThan(198)
  expect(await svg.locator('path[data-source]').evaluateAll(nodes => nodes.filter(n => n.getAttribute('data-source') === n.getAttribute('data-target')).length)).toBeGreaterThan(0)
  await page.screenshot({ path: testInfo.outputPath('review-topology.png'), fullPage: true })
  await page.getByRole('button', { name: '解剖 3D', exact: true }).click()
  await page.getByRole('button', { name: '单步' }).click()
  await expect(canvas).toHaveAttribute('data-displayed-nodes', '220', { timeout: 120000 })
  await expect(page.getByText('R1–R6', { exact: false })).toBeVisible()
  const cameraPosition = await canvas.getAttribute('data-camera-position')
  await page.getByLabel('神经元 ID').fill('10002')
  await page.getByRole('button', { name: '加载骨架' }).click()
  await expect(page.getByText('BODY 10002', { exact: true })).toBeVisible({ timeout: 120000 })
  await expect(canvas).toHaveAttribute('data-scene-instance', 'original')
  await expect(canvas).toHaveAttribute('data-camera-position', cameraPosition!)
  await expect(canvas).toHaveAttribute('data-displayed-nodes', '220')
  await expect(page.getByRole('button', { name: '40K 强连接' })).toHaveAttribute('aria-pressed', 'false')
  await page.screenshot({ path: testInfo.outputPath('review-anatomy.png'), fullPage: true })
  expect(errors).toEqual([])
  await page.unrouteAll({ behavior: 'wait' })
})

test('driving controls expose learning, stepping and reset', async ({ page }) => {
  await page.route('**/api/**', async route => {
    const url = route.request().url().replace('127.0.0.1:5174', '127.0.0.1:8000')
    await route.continue({ url })
  })
  await page.goto('http://127.0.0.1:5174/')
  await expect(page.getByText('障碍驾驶实验')).toBeVisible({ timeout: 120000 })
  await expect(page.getByLabel('多巴胺可塑性')).toBeChecked()
  await page.getByRole('button', { name: '单步' }).click()
  await expect(page.locator('.telemetry').getByText(/\/1571$/)).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: '清除学习' }).click()
  await expect(page.getByText('0/1571')).toBeVisible({ timeout: 120000 })
  await page.unrouteAll({ behavior: 'wait' })
})
